title: weithink
description: weithink's GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
github:
  zip_url: http://example.com/download.zip
  another_url: another value
  repository_url:https://www.weithink.cn
lang:zh-CN
